### ISSUE TITLE
Broken dashboard with plugin

### ISSUE THREAD

**Issue by Jelena1** [WordPress/gutenberg-examples#36]
I have 5-6 warnings in dashboard when your plugin is activated. Can't use it at all because of broken dashboard. Is it working at all?

**Comment by Jelena1** [comment]
With or without wp-config active all the same.

**Comment by ajitbohra** [comment]
For each of the examples that include es next example, `npm install && npm run build` commands is required to build the plugin. You are seeing warnings as build files for esnext examples are missing.

@Jelena1 kindly share the screenshot of warning on screeen or browser console

**Comment by Jelena1** [comment]
![image 1](https://user-images.githubusercontent.com/11799943/44620652-79fe3b80-a898-11e8-8eed-4b686a87e323.png)

**Comment by ajitbohra** [comment]
@Jelena1 Build files for esnext examples are missing you need to run `npm install && npm run build`

@aduth should we include build files for esnext examples ?

**Comment by Jelena1** [comment]
I don't understand what is that. Can't you have prepared plugin for usage with all what is needed?

**Comment by aduth** [comment]
We shouldn't commit the build artifacts ([context](https://stackoverflow.com/questions/893913/should-i-store-generated-code-in-source-control)), but we could use [GitHub's Releases feature](https://help.github.com/articles/about-releases/) to attach a pre-built zip to a tagged version ([example for a theme project of my own](https://github.com/aduth/dones/releases)).

Since the purpose of this project is to serve as a starting point for development, it seems sensible to me that it's expected for someone to build the files to be able to work with them. Our instructions could probably be more clear on what's required for this though (i.e. not assuming prior knowledge of [Node](https://nodejs.org/en/) and [npm](https://www.npmjs.com/)).

An argument could be made that it'd be useful to demo the examples without building them, but since the non- `esnext` versions are made available and don't require a build, this should already be possible.

@Jelena1 For the time being, you could edit the `index.php` file and comment each of the `include` lines which point to an  "esnext" folder (add `//` before the line). I think this would stop the warnings.

https://github.com/WordPress/gutenberg-examples/blob/34eb4134130a8e5dfa5b33e66e09be47ccc02d3e/index.php#L16

https://github.com/WordPress/gutenberg-examples/blob/34eb4134130a8e5dfa5b33e66e09be47ccc02d3e/index.php#L19

https://github.com/WordPress/gutenberg-examples/blob/34eb4134130a8e5dfa5b33e66e09be47ccc02d3e/index.php#L21

https://github.com/WordPress/gutenberg-examples/blob/34eb4134130a8e5dfa5b33e66e09be47ccc02d3e/index.php#L23

**Comment by aduth** [comment]
Action items (enhancement):

- Improve documentation for building the examples
- Provide pre-built distributable with Releases
- Allow easier independent use of example folders (i.e. add plugin manifest to each subfolder's `index.php`)
