### ISSUE TITLE
Fatal Error: undefined function gutenberg_get_jed_locale_data()

### ISSUE THREAD

**Issue by oldmankit** [WordPress/gutenberg-examples#59]
Updating to Wordpress 5.0 today broke my site. I think it is due to the following error caused by this plugin:

`Fatal error: Call to undefined function gutenberg_get_jed_locale_data() in directory\index.php on line 55`

This is being called in 05-recipe-card/index.php

I'm not sure how to fix it and would really appreciate help!

**Comment by nicowolf** [comment]
Same here. The function get_jed_locale_data() was obiously [removed from core](https://github.com/ampproject/amp-wp/pull/1634), see also [here](https://core.trac.wordpress.org/changeset/43910). The gutenberg-examples worked fine in 4.9.8, in 5.0 a fatal error occurs. The error is due to this line:

`json_encode( ! function_exists( 'wp_get_jed_locale_data' ) ? gutenberg_get_jed_locale_data( 'gutenberg-examples' ) : wp_get_jed_locale_data( 'gutenberg-examples' ) )`

**Comment by swissspidy** [comment]
The correct way to load translations is to use `wp_set_script_translations()`. I‘ll try to update the examples accordingly in the next few days.

**Comment by nicowolf** [comment]
@swissspidy Not being sure if I completely grasped the usage of wp_set_script_translations() I’ve created a [pull request](#60) anyway.
